server:
  port: 8081
  servlet:
    context-path: /api/v1

# better readable jackson serialization format
spring:
#  jackson:
#    serialization:
#      INDENT_OUTPUT: true

  flyway:
    enabled: true
    baseline-on-migration: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
#  spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
  h2:
    console:
      # URL: jdbc:h2:mem:testdb
      enabled: true
#
#  devtools:
#    restart:
#      enabled: true

jwt:
  header: Authorization
  # This token must be encoded using Base64 with mininum 88 Bits (you can type `echo 'secret-key'|base64` on your command line)
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # token is valid 24 hours
  token-validity-in-seconds: 86400
  # valid 30 hours
  token-validity-in-seconds-for-remember-me: 108000
  route:
    authentication:
      path: auth
      refresh: refresh
#
#logging:
#  level:
#    org.zerhusen.security: DEBUG
#    org.springframework.security: DEBUG


#flyway:
#  user: databaseUser
#  password: databasePassword
#  schemas: app-db
#  url: jdbc:h2:mem:testdb
#  locations: filesystem:db/migration

